blank_issues_enabled: false
contact_links:
  - name: suyu Discord
    url: https://discord.com/invite/suyu
    about: If you are experiencing an issue with suyu, and you need tech support, or if you have a general question, try asking in the official suyu Discord linked here. Piracy is not allowed.
